package com.mentalfrostbyte.jello.music.tools;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.mentalfrostbyte.jello.music.Track;
import com.mentalfrostbyte.jello.music.lyrics.Lyrics;
import com.mentalfrostbyte.jello.music.lyrics.LyricsParser;
import com.mentalfrostbyte.jello.music.netease.NeteaseApi;
import com.mentalfrostbyte.jello.music.netease.NeteaseSession;
import com.mentalfrostbyte.jello.music.qq.QQMusicApi;
import com.mentalfrostbyte.jello.music.qq.QQMusicMatcher;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Exports live NetEase/QQ lyric fixtures for the Apple Watch Swift port.
 *
 * Run with 6-8 search queries:
 *   mvn -q -DskipTests test-compile dependency:build-classpath -Dmdep.outputFile=target/test.cp
 *   java -cp "target/test-classes:target/classes:$(cat target/test.cp)" \
 *     com.mentalfrostbyte.jello.music.tools.LyricFixtureExporter \
 *     target/watch-lyrics "Lemon 米津玄師" "起风了" "Blinding Lights" ...
 *
 * Each song gets raw service payloads plus the Java parser's normalized JSON.
 * Login cookies are read through NeteaseSession exactly like the player, but cookie
 * values are never written to the fixture output.
 */
public final class LyricFixtureExporter {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    private LyricFixtureExporter() {}

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("Usage: LyricFixtureExporter <output-dir> <query> [query ...]");
            System.err.println("Pass 6-8 representative songs: YRC, LRC-only, translated, romanized, instrumental, and QQ fallback.");
            System.exit(2);
        }

        Path output = Path.of(args[0]);
        Files.createDirectories(output);
        Path sessionDir = output.resolve(".session");
        Files.createDirectories(sessionDir);

        NeteaseApi netease = new NeteaseApi(new NeteaseSession(sessionDir));
        JsonArray manifest = new JsonArray();

        for (int i = 1; i < args.length; i++) {
            String query = args[i];
            try {
                JsonObject entry = exportOne(netease, output, query, i);
                manifest.add(entry);
                System.out.printf("[%d/%d] %s -> %s%n", i, args.length - 1, query, entry.get("slug").getAsString());
            } catch (Exception e) {
                JsonObject failed = new JsonObject();
                failed.addProperty("query", query);
                failed.addProperty("error", e.getClass().getSimpleName() + ": " + String.valueOf(e.getMessage()));
                manifest.add(failed);
                System.err.printf("[%d/%d] %s FAILED: %s%n", i, args.length - 1, query, e);
            }
        }

        JsonObject root = new JsonObject();
        root.addProperty("format", 1);
        root.addProperty("note", "Generated by Sigma-Modern LyricFixtureExporter; contains lyrics but no login cookie values.");
        root.add("entries", manifest);
        write(output.resolve("manifest.json"), GSON.toJson(root));
    }

    private static JsonObject exportOne(NeteaseApi netease, Path output, String query, int ordinal) throws Exception {
        List<Track> results = netease.search(query, 8);
        if (results.isEmpty()) throw new IllegalStateException("NetEase search returned no songs");
        Track track = results.getFirst();
        long songId = NeteaseApi.songId(track);
        NeteaseApi.LyricTexts ne = netease.lyrics(songId);

        String slug = String.format("%02d-%d", ordinal, songId);
        Path dir = output.resolve(slug);
        Files.createDirectories(dir);

        write(dir.resolve("netease-yrc.txt"), ne.yrc());
        write(dir.resolve("netease-lrc.txt"), ne.lrc());
        write(dir.resolve("netease-translation.lrc"), ne.translation());
        write(dir.resolve("netease-romanization.lrc"), ne.romanization());

        Lyrics neTranslation = LyricsParser.lrc(ne.translation());
        Lyrics neRomanization = LyricsParser.lrc(ne.romanization());
        Lyrics yrc = LyricsParser.attach(LyricsParser.yrc(ne.yrc()), neTranslation, neRomanization);
        Lyrics lrc = LyricsParser.attach(LyricsParser.lrc(ne.lrc()), neTranslation, neRomanization);

        JsonObject parsed = new JsonObject();
        parsed.add("neteaseYrc", lyricsJson(yrc));
        parsed.add("neteaseLrc", lyricsJson(lrc));

        JsonObject qq = exportQQ(track, dir);
        if (qq.has("parsed")) parsed.add("qqQrc", qq.get("parsed"));

        write(dir.resolve("parsed-java.json"), GSON.toJson(parsed));

        JsonObject metadata = new JsonObject();
        metadata.addProperty("query", query);
        metadata.add("track", trackJson(track));
        metadata.addProperty("instrumental", ne.instrumental());
        metadata.add("qq", qq);
        write(dir.resolve("metadata.json"), GSON.toJson(metadata));

        JsonObject manifest = new JsonObject();
        manifest.addProperty("query", query);
        manifest.addProperty("slug", slug);
        manifest.addProperty("neteaseId", songId);
        manifest.addProperty("title", track.title());
        manifest.addProperty("artist", track.artist());
        manifest.addProperty("hasYrc", !ne.yrc().isBlank());
        manifest.addProperty("hasLrc", !ne.lrc().isBlank());
        manifest.addProperty("hasTranslation", !ne.translation().isBlank());
        manifest.addProperty("hasRomanization", !ne.romanization().isBlank());
        manifest.addProperty("instrumental", ne.instrumental());
        manifest.addProperty("hasQrc", qq.has("hasQrc") && qq.get("hasQrc").getAsBoolean());
        return manifest;
    }

    private static JsonObject exportQQ(Track track, Path dir) {
        JsonObject out = new JsonObject();
        try {
            String artist = track.artist().split(" / ")[0];
            List<QQMusicApi.QQTrack> candidates = QQMusicApi.search(track.title() + " " + artist, 8);
            QQMusicMatcher.Match match = QQMusicMatcher.match(candidates, track.title(), artist, track.durationMs());
            if (match == null) {
                out.addProperty("matched", false);
                out.addProperty("hasQrc", false);
                return out;
            }

            QQMusicApi.QQLyrics found = QQMusicApi.fetchLyrics(match.track().songId());
            out.addProperty("matched", true);
            out.addProperty("songId", match.track().songId());
            out.addProperty("songMid", match.track().songMid());
            out.addProperty("score", match.score());

            if (found == null) {
                out.addProperty("hasQrc", false);
                return out;
            }

            String qrc = found.qrc() == null ? "" : found.qrc();
            String translation = found.translation() == null ? "" : found.translation();
            String romanization = found.romanization() == null ? "" : found.romanization();

            write(dir.resolve("qq-qrc.txt"), qrc);
            write(dir.resolve("qq-translation.lrc"), translation);
            write(dir.resolve("qq-romanization.qrc"), romanization);

            Lyrics parsed = LyricsParser.qrc(qrc);
            Lyrics qqTranslation = translation.isBlank() ? null : LyricsParser.lrc(translation);
            Lyrics qqRomanization = romanization.isBlank() ? null : LyricsParser.qrc(romanization);
            parsed = LyricsParser.attach(parsed, qqTranslation, qqRomanization);

            out.addProperty("hasQrc", parsed.kind() == Lyrics.Kind.WORD);
            out.add("parsed", lyricsJson(parsed));
        } catch (Exception e) {
            out.addProperty("matched", false);
            out.addProperty("hasQrc", false);
            out.addProperty("error", e.getClass().getSimpleName() + ": " + String.valueOf(e.getMessage()));
        }
        return out;
    }

    private static JsonObject trackJson(Track track) {
        JsonObject out = new JsonObject();
        out.addProperty("id", track.id());
        out.addProperty("title", track.title());
        out.addProperty("artist", track.artist());
        out.addProperty("album", track.album());
        out.addProperty("tag", track.tag());
        out.addProperty("durationMs", track.durationMs());
        if (track.cover() != null) out.addProperty("cover", track.cover());
        return out;
    }

    private static JsonObject lyricsJson(Lyrics lyrics) {
        JsonObject out = new JsonObject();
        out.addProperty("kind", lyrics.kind().name());
        JsonArray lines = new JsonArray();

        for (Lyrics.Line line : lyrics.lines()) {
            JsonObject row = new JsonObject();
            row.addProperty("startMs", line.startMs());
            row.addProperty("endMs", line.endMs());
            row.addProperty("text", line.text());
            if (line.translation() != null) row.addProperty("translation", line.translation());
            if (line.romanization() != null) row.addProperty("romanization", line.romanization());

            JsonArray words = new JsonArray();
            for (Lyrics.Word word : line.words()) {
                JsonObject w = new JsonObject();
                w.addProperty("startMs", word.startMs());
                w.addProperty("durationMs", word.durationMs());
                w.addProperty("text", word.text());
                words.add(w);
            }
            row.add("words", words);
            lines.add(row);
        }

        out.add("lines", lines);
        return out;
    }

    private static void write(Path path, String text) throws Exception {
        Files.writeString(path, text == null ? "" : text, StandardCharsets.UTF_8);
    }
}
